// Merges the student-app rules (firestore.rules) and the editor's report fragment (firestore.editor-reports.rules)
// into the question bank editor's live rules (primary-math-sg, database "default"). Pure; used by deploy-rules.mjs
// and the merged-rules tests.
//
// The editor's own rules stay byte-for-byte; the student part sits between the BEGIN/END markers just before the
// closing braces, and is replaced on every merge (so re-running is idempotent and picks up rule changes).
export const BEGIN = "    // ==== BEGIN student app (generated by backend/scripts/deploy-rules.mjs, do not edit here) ====";
export const END = "    // ==== END student app ====";
const EDITOR_HELPERS = ["isMaster", "inScope", "vol", "signedIn"]; // the report fragment relies on these

/** Body of `match /databases/{database}/documents { ... }`. */
function documentsBody(src) {
  const head = "match /databases/{database}/documents {";
  const at = src.indexOf(head);
  if (at < 0) throw new Error("no documents match block");
  const brace = at + head.length - 1; // the block's own "{" (not the one in {database})
  let depth = 0;
  for (let i = brace; i < src.length; i++) {
    if (src[i] === "{") depth++;
    else if (src[i] === "}" && --depth === 0) return { start: brace + 1, end: i };
  }
  throw new Error("unbalanced braces");
}

/** Removes `match <path> { ... }` (with its nested blocks) from a rules body. */
function dropMatch(body, path) {
  const at = body.indexOf(`match ${path} {`);
  if (at < 0) return body;
  let depth = 0, i = at + `match ${path} {`.length - 1;
  for (; i < body.length; i++) {
    if (body[i] === "{") depth++;
    else if (body[i] === "}" && --depth === 0) break;
  }
  const lineStart = body.lastIndexOf("\n", at) + 1;
  return body.slice(0, lineStart) + body.slice(body.indexOf("\n", i) + 1);
}

const functionNames = (src) => [...src.matchAll(/function\s+(\w+)\s*\(/g)].map((m) => m[1]);
const fnDef = (src, name) => src.match(new RegExp(`function\\s+${name}\\s*\\([^)]*\\)\\s*\\{[^\\n]*`))?.[0]?.replace(/\s+/g, " ");

/** The editor rules without a previous student section. */
export function editorPart(live) {
  const b = live.indexOf(BEGIN), e = live.indexOf(END);
  if (b < 0 && e < 0) return live;
  if (b < 0 || e < b) throw new Error("student markers are broken in the live rules");
  return live.slice(0, live.lastIndexOf("\n", b) + 1) + live.slice(live.indexOf("\n", e) + 1);
}

export function mergeRules(live, student, reportsFragment) {
  const editor = editorPart(live);
  for (const h of EDITOR_HELPERS) if (!functionNames(editor).includes(h)) throw new Error(`editor rules lack ${h}(); the report rules need it`);
  const s = documentsBody(student);
  let body = student.slice(s.start, s.end);
  body = dropMatch(body, "/config/{doc}"); // editor-owned collection (its catch-all: master only)
  body = dropMatch(body, "/{document=**}"); // deny-all adds nothing (rules only grant)
  // signedIn() exists on both sides: keep the editor's, but only if it means the same
  if (fnDef(student, "signedIn") && fnDef(student, "signedIn") !== fnDef(editor, "signedIn")) throw new Error("signedIn() differs between editor and student rules");
  body = body.replace(/^[ \t]*function signedIn\(\)[^\n]*\n/m, "");
  const clash = functionNames(body).filter((n) => functionNames(editor).includes(n));
  if (clash.length) throw new Error(`function name clash with the editor rules: ${clash.join(", ")}`);
  const d = documentsBody(editor);
  const studentPart = body.replace(/^\s+|\s+$/g, "");
  const section = `${BEGIN}\n${studentPart ? `    ${studentPart}\n\n` : ""}${reportsFragment.replace(/\s+$/, "")}\n${END}\n`;
  const before = editor.slice(0, d.end).replace(/[ \t]*$/, "");
  return `${before}${section}  ${editor.slice(d.end)}`;
}
