"""Make one map per chapter: the artist's river with that chapter's own themed island, and measure the route.

Writes assets/ui/map-bg-N.webp (N = 1..12), src/theme/mapPaths.ts (route; first-guess spots) and the map aspect
ratios in src/theme/assets.ts. The art is used exactly as drawn (the pack is "Game Level Map for Water Games": every
theme is a flooded island on a river): chapter N shows island N (1 yacht marina, 2 flooded city, 3 suburbia,
4 military base, 5 ice, 6 mountains, 7 volcano, 8 city at night, 9 garbage dump, 10 theme park, 11 industrial
platform, 12 space base) on the river, and no other island, so every map has its own theme.

    pip install pillow numpy scipy
    python scripts/map-scenes.py                                    # uses design/source-assets/map-pack/layers/
    python scripts/map-spots.py assets/content/P6/curriculum.json   # then: even button spots

The layers (river.png, island-N.png, layers.json) are rendered once from the pack's PSD by scripts/map-layers.py.

How it works:
1. Per chapter, a portrait window centred on the island and tall enough for its buttons, is cut
   from river + island N; island N's outline is the only obstacle.
2. A distance transform gives clearance to the island; dynamic programming finds a smooth bottom→top route through
   the water that maximises clearance.
3. Node spots: first guesses only; scripts/map-spots.py re-places the buttons evenly spaced.
"""
import json
import math
import os
import re
import sys

import numpy as np
from PIL import Image
from scipy.ndimage import distance_transform_edt

Image.MAX_IMAGE_PIXELS = None
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "theme", "mapPaths.ts")
PACK_DIR = os.path.join(HERE, "..", "..", "..", "design", "source-assets", "map-pack")
LAYERS = os.path.join(PACK_DIR, "layers")
ASSETS_TS = os.path.join(HERE, "..", "src", "theme", "assets.ts")
CURRICULUM = os.path.join(HERE, "..", "assets", "content", "P6", "curriculum.json")

MIN_ASPECT = 1.8
ROW = 270  # map pixels between button rows (~63pt on a 390pt-wide phone at CW = 1680)
GROUP_GAP = 2  # rows between level groups
JIT = 0.45  # a button may move this many rows up/down from its even row to stay in open water
BTN = 103  # button radius in map pixels (48pt button ≈ 207px wide at 1680px = 390pt)
CW = 1680  # crop width in map pixels (the full map is 2048 wide); fits the widest island (1660)
ISLAND_SIDE = {o: ("left" if o % 2 else "right") for o in range(1, 13)}
OUT_W = 1080
D = 8  # analysis downsample
DEBUG = os.environ.get("DEBUG") == "1"


def route(clr, cap=300.0, lam=6.0, k=6):
    R, C = clr.shape
    score = np.minimum(clr, cap)
    score = np.where(clr < 120, score - 5000, score)
    acc, back = score[R - 1].copy(), np.zeros((R, C), int)
    for r in range(R - 2, -1, -1):
        best, arg = np.full(C, -1e18), np.zeros(C, int)
        for dx in range(-k, k + 1):
            sh = np.roll(acc, dx)
            if dx > 0:
                sh[:dx] = -1e18
            elif dx < 0:
                sh[dx:] = -1e18
            v = sh - lam * abs(dx)
            upd = v > best
            best[upd], arg[upd] = v[upd], (np.arange(C) - dx)[upd]
        acc, back[r] = best + score[r], arg
    x = int(np.argmax(acc))
    path = [(x, 0)]
    for r in range(R - 1):
        x = int(back[r][x])
        path.append((x, r + 1))
    P = np.array([(px * D, py * D) for px, py in path], float)
    P[:, 0] = np.convolve(np.pad(P[:, 0], 4, mode="edge"), np.ones(9) / 9, mode="valid")
    return P


def greedy(L, cs, c, d, n):
    picks, last = [], -1e18
    for i in range(len(L) - 1, -1, -1):
        s = L[-1] - L[i]
        if cs[i] >= c and s - last >= d:
            picks.append(i)
            last = s
            if len(picks) == n:
                return picks
    return None


def main(curriculum):
    river = Image.open(os.path.join(LAYERS, "river.png")).convert("RGB")
    W, H = river.size
    where = json.load(open(os.path.join(LAYERS, "layers.json")))
    aspects = {}

    counts = {t["order"]: len(t["subtopics"]) for t in json.load(open(curriculum))["topics"]}
    lines = [
        "// GENERATED by apps/mobile/scripts/map-scenes.py from the river map pack. Do not edit by hand.",
        "// Per chapter map: `path` = safest route through open water, top → bottom, as [x, y, open] with x/y as",
        "// fractions of the map image (open = 0 where the route passes behind an object; no trail dots there).",
        "// `spots` = where the level buttons sit (x, y fractions), bottom first: every Level 1, then Level 2, then Level 3;",
        "// evenly spaced by scripts/map-spots.py (run it after this script).",
        "export interface MapPath { path: [number, number, 0 | 1][]; nodes: number[]; spots?: [number, number][] }",
        "",
        "export const mapPaths: MapPath[] = [",
    ]
    for o in range(1, 13):
        island = Image.open(os.path.join(LAYERS, f"island-{o}.png")).convert("RGBA")
        scene = river.convert("RGBA")
        sheet = Image.new("RGBA", (W, H))
        sheet.paste(island, tuple(where[str(o)]))
        scene.alpha_composite(sheet)
        # Only this chapter's island is in the way. Its PSD group also holds its wave lines, which are already on the
        # river, so pixels that look the same as the river underneath are water, not island.
        lay = np.asarray(sheet).astype(np.int16)
        diff = np.abs(np.asarray(scene.convert("RGB")).astype(np.int16) - np.asarray(river).astype(np.int16)).sum(axis=2)
        obs = (lay[..., 3] > 40) & (diff > 24)
        del lay, diff
        rows = np.nonzero(obs.any(axis=1))[0]
        y0, y1 = int(rows[0]), int(rows[-1])
        cols = np.nonzero(obs.any(axis=0))[0]
        cx0 = int(min(W - CW, max(0, (cols[0] + cols[-1]) // 2 - CW // 2)))
        print(f"map {o}: island x {cols[0]}..{cols[-1]} (width {cols[-1] - cols[0]}), rows {y0}..{y1}")
        n = 3 * counts.get(o, 5)  # one button per level of every subtopic (LV1 row at the bottom, LV3 at the top)
        # Crop CW wide on the island's side (islands alternate left/right), so each map shows its own theme and only
        # glimpses of the neighbours; the river between the islands stays in view.
        # Buttons sit in evenly spaced rows up the map (ROW apart; GROUP_GAP rows between the Level 1, 2 and 3 groups),
        # each at the most open spot in its row near the river, leaving room beside it for the subtopic name.
        per = n // 3
        slots = [i + (i // per) * (GROUP_GAP - 1) for i in range(n)]  # bottom first
        result = None
        for grow in (1.0,):  # one island on open water always leaves room
            for c0 in (cx0,):  # always centred on the island, so its theme fills the map
                h = int(max(CW * MIN_ASPECT, (y1 - y0) + 240, (slots[-1] + 2) * ROW) * grow)
                top = max(0, min(H - h, (y0 + y1) // 2 - h // 2))
                free = ~obs[top:top + h:D, c0:c0 + CW:D]
                free[:, :1] = free[:, -1:] = False
                clr = distance_transform_edt(free) * D
                P = route(clr)  # river route, used to keep buttons near the water path
                rx = lambda y: float(np.interp(y, P[:, 1], P[:, 0]))
                band = int(BTN / 2 / D)
                xs_ok = np.arange(int(0.08 * CW / D), int(0.92 * CW / D))  # leave room for a name beside the button
                R = clr.shape[0]
                # best open spot in every analysis row: clearance over a button-tall band
                colmins = [clr[max(0, r - band):r + band + 1].min(axis=0)[xs_ok] for r in range(R)]
                rowbest = np.array([c.max() for c in colmins])
                jit = int(ROW * JIT / D)

                def win(y):  # best clearance within ±JIT of a row
                    r = int(y / D)
                    return rowbest[max(0, r - jit):min(R, r + jit + 1)].max()
                best = (-1, None)
                for step in np.linspace(ROW, ROW * 1.35, 8):
                    span = slots[-1] * step
                    for b0 in np.arange(ROW * 0.5, max(ROW * 0.5 + 1, h - span - ROW * 0.5), D * 2):
                        ys = [h - b0 - sl * step for sl in slots]
                        if min(ys) < ROW * 0.4:
                            continue
                        c = min(win(y) for y in ys)
                        if c > best[0]:
                            best = (c, ys)
                if result is None or best[0] > result[0]:
                    result = (best[0], c0, h, top, best[1], colmins, R, jit, rx, xs_ok)
            if result[0] >= 0.6 * BTN:
                break
        _, c0, h, top, best_ys, colmins, R, jit, rx, xs_ok = result
        best = (result[0], best_ys)
        spots, worst = [], 1e9
        for y0r in best[1]:
            r0 = int(y0r / D)
            cand = []
            for r in range(max(0, r0 - jit), min(R, r0 + jit + 1)):
                colmin = colmins[r]
                score = 4 * np.minimum(colmin, BTN) - 0.08 * np.abs(xs_ok * D - rx(r * D)) - 1.5 * abs(r - r0) * D
                j = int(np.argmax(score))
                cand.append((score[j], xs_ok[j] * D, r * D, colmin[j]))
            _, x, y, c = max(cand)
            spots.append((x, y))
            worst = min(worst, c)
        lo = worst
        idx = np.linspace(0, len(P) - 1, 90).astype(int)
        coarse = P[idx]
        nodes = []
        crop = scene.convert("RGB").crop((c0, top, c0 + CW, top + h)).resize((OUT_W, round(h * OUT_W / CW)), Image.LANCZOS)
        crop.save(os.path.join(HERE, "..", "assets", "ui", f"map-bg-{o}.webp"), quality=82, method=6)
        aspects[o] = round(h / CW, 3)
        print(f"map {o}: aspect {h / CW:.3f}, {n} nodes, narrowest spot fits a {round(2 * lo / CW * 390)}pt button")
        pts = [f"[{round(x / CW, 4)}, {round(y / h, 4)}, 1]" for x, y in coarse]
        sp = [f"[{round(x / CW, 4)}, {round(y / h, 4)}]" for x, y in spots]
        lines += [f"  {{ // map {o}", f"    path: [{', '.join(pts)}],", f"    nodes: [],", f"    spots: [{', '.join(sp)}],", "  },"]
    lines.append("];")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("wrote", OUT)
    ts = open(ASSETS_TS).read()
    for o, a in aspects.items():
        ts, k = re.subn(rf'(map-bg-{o}\.webp"\), aspect: )[\d.]+', rf"\g<1>{a}", ts)
        assert k == 1, f"aspect for map {o} not found in assets.ts"
    open(ASSETS_TS, "w").write(ts)
    print("wrote", ASSETS_TS)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else CURRICULUM)
