"""Build one distinct map per chapter from the river-map pack's 12 island sections, and measure button spots.

Writes assets/ui/map-bg-N.webp (N = 1..12) and src/theme/mapPaths.ts.

    pip install pillow numpy
    python scripts/map-sections.py /path/to/unzipped-pack assets/content/P6/curriculum.json

How it works:
1. Section N (assets/png/NN_*.png = island + its stream swirls) is placed flush against the side its island was cut
   on, on the pack's water colour, in a tall portrait canvas. Extra water above/below gets the section's stream art.
2. The island layer alone (assets/png/separated/NN_*.png, without the stream) is the obstacle mask.
3. A winding trail through the open water lane beside the island (kept a node-column half-width clear of the island
   and the screen edges), with n buttons evenly spaced along it.
"""
import glob
import json
import os
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
D = 8  # analysis downsample

W = 2048  # canvas width (pack scale); exported at OUT_W
OUT_W = 1080
WATER = (108, 221, 231, 255)
ISLAND_FRAC = 0.6  # island takes at most this share of the width; the rest is the water lane for buttons
MIN_ASPECT = 1.75
R = 0.19  # half the node column (button + name label) as a share of width: trail keeps this far from obstacles/edges


def find_offset(big, small, s=8):
    """Where the island layer sits inside the combined section image (alpha correlation)."""
    A = np.asarray(big.resize((big.width // s, big.height // s)))[..., 3] > 40
    B = np.asarray(small.resize((small.width // s, small.height // s)))[..., 3] > 40
    best = (-1, 0, 0)
    for y in range(A.shape[0] - B.shape[0] + 1):
        for x in range(A.shape[1] - B.shape[1] + 1):
            v = (A[y:y + B.shape[0], x:x + B.shape[1]] & B).sum()
            if v > best[0]:
                best = (v, y * s, x * s)
    return best[1], best[2]


def main(pack, curriculum):
    counts = {t["order"]: len(t["subtopics"]) for t in json.load(open(curriculum))["topics"]}
    lines = [
        "// GENERATED by apps/mobile/scripts/map-sections.py from the river map pack. Do not edit by hand.",
        "// Per chapter map: `path` = safest route through open water, top → bottom, as [x, y, open] with x/y as",
        "// fractions of the map image (open = 0 where the route passes behind an object; no trail dots there).",
        "// `nodes` = where P6 subtopic buttons sit, as arc-length fractions along `path` (0 = top), start (bottom) first.",
        "export interface MapPath { path: [number, number, 0 | 1][]; nodes: number[] }",
        "",
        "export const mapPaths: MapPath[] = [",
    ]
    meta = []
    for o in range(1, 13):
        sec = Image.open(glob.glob(os.path.join(pack, f"assets/png/{o:02d}_*.png"))[0]).convert("RGBA")
        isl = Image.open([f for f in glob.glob(os.path.join(pack, f"assets/png/separated/{o:02d}_*.png")) if "stream" not in f][0]).convert("RGBA")
        stream = Image.open(glob.glob(os.path.join(pack, f"assets/png/separated/{o:02d}_*_stream.png"))[0]).convert("RGBA")
        ia = np.asarray(isl)[..., 3] > 40
        side = "left" if ia[:, :12].mean() > ia[:, -12:].mean() else "right"
        oy, ox = find_offset(sec, isl)
        s = min(1.0, ISLAND_FRAC * W / isl.width, W / sec.width)
        sw, sh = round(sec.width * s), round(sec.height * s)
        n = counts.get(o, 5)
        H = max(int(W * MIN_ASPECT), sh + int(0.22 * W), (n + 1) * 520)  # room for n buttons a min gap apart
        canvas = Image.new("RGBA", (W, H), WATER)
        # Stream swirls in the open water above and below the island (mirrored for variety).
        st = stream.resize((round(stream.width * s), round(stream.height * s)))
        top_y, bot_y = (H - sh) // 2, (H - sh) // 2 + sh
        sx = W - st.width if side == "left" else 0
        if top_y > st.height * 0.3:
            canvas.alpha_composite(st.transpose(Image.FLIP_TOP_BOTTOM), (sx, max(0, top_y - st.height)))
        if H - bot_y > st.height * 0.3:
            canvas.alpha_composite(st.transpose(Image.FLIP_LEFT_RIGHT), (sx, min(H - st.height, bot_y)))
        x0 = 0 if side == "left" else W - sw
        canvas.alpha_composite(sec.resize((sw, sh)), (x0, top_y))
        obs = np.zeros((H, W), bool)
        mask = np.asarray(isl.resize((round(isl.width * s), round(isl.height * s))))[..., 3] > 40
        my, mx = top_y + round(oy * s), x0 + round(ox * s)
        y1, x1 = min(H, my + mask.shape[0]), min(W, mx + mask.shape[1])
        obs[my:y1, mx:x1] |= mask[: y1 - my, : x1 - mx]

        out = canvas.convert("RGB").resize((OUT_W, round(H * OUT_W / W)), Image.LANCZOS)
        out.save(os.path.join(HERE, "..", "assets", "ui", f"map-bg-{o}.webp"), quality=82, method=6)
        meta.append((o, round(H / W, 3), side))

        # Winding trail: per row, the open lane between the island (plus a margin) and the far screen edge;
        # the trail swings across that lane like a river path, smoothed, and buttons sit evenly along it.
        r = R * W
        ys = np.arange(0, H, D)
        occ = obs[::D, ::D]
        if side == "left":
            edge = np.array([np.nonzero(row)[0].max() if row.any() else 0 for row in occ]) * D
        else:
            edge = np.array([np.nonzero(row)[0].min() if row.any() else W for row in occ]) * D
        win = int(r * 1.1 / D)  # a button + label spans this many rows; use the worst row nearby
        if side == "left":
            edge = np.array([edge[max(0, i - win):i + win + 1].max() for i in range(len(edge))])
            a, b = np.maximum(r, edge + r), np.full(len(edge), W - r)
        else:
            edge = np.array([edge[max(0, i - win):i + win + 1].min() for i in range(len(edge))])
            a, b = np.full(len(edge), r), np.minimum(W - r, edge - r)
        b = np.maximum(a, b)
        phase = o * 1.7
        wave = 0.5 + 0.42 * np.sin(2 * np.pi * ys / (0.95 * W) + phase)
        xs = a + (b - a) * wave
        kern = np.ones(31) / 31
        xs = np.convolve(np.pad(xs, 15, mode="edge"), kern, mode="valid")
        xs = np.clip(xs, a, b)
        coarse = np.c_[xs, ys][np.linspace(0, len(ys) - 1, 90).astype(int)]
        Pd = np.c_[xs, ys]
        L = np.r_[0, np.cumsum(np.hypot(*np.diff(Pd, axis=0).T))]
        lo = float(np.min(np.where(side == "left", xs - edge, edge - xs)))
        nodes = [round(float(t), 4) for t in np.linspace(0.85, 0.08, n)]  # arc-length fractions, start (bottom) first
        pts = [f"[{round(x / W, 4)}, {round(y / H, 4)}, 1]" for x, y in coarse]
        lines += [f"  {{ // map {o}", f"    path: [{', '.join(pts)}],", f"    nodes: [{', '.join(map(str, nodes))}],", "  },"]
        print(f"map {o} ({side}, aspect {H / W:.3f}): {n} nodes, closest island gap {round(lo / W * 390)}pt from trail centre")
    lines.append("];")
    open(os.path.join(HERE, "..", "src", "theme", "mapPaths.ts"), "w").write("\n".join(lines) + "\n")
    print("meta (order, aspect, island side):", meta)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
