// Firebase deploys functions/ standalone (it is NOT an npm workspace member), so it cannot import
// @p6/shared. This copies the pure shared modules (types, game rules, callable contract) from packages/shared
// into src/shared. Runs automatically before `build`, `typecheck` and `test`. src/shared is generated and git-ignored.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const from = path.resolve(here, "../../../packages/shared/src");
const to = path.resolve(here, "../src/shared");
const FILES = ["types", "gameRules", "api", "stars"]; // answer.ts is app/content only
fs.mkdirSync(to, { recursive: true });
for (const f of FILES) {
  let src = fs.readFileSync(path.join(from, `${f}.ts`), "utf8");
  // NodeNext resolution needs explicit extensions on relative imports.
  src = src.replace(/from "\.\/(\w+)"/g, 'from "./$1.js"');
  fs.writeFileSync(path.join(to, `${f}.ts`), `// GENERATED by scripts/copy-shared.mjs from packages/shared/src/${f}.ts. Do not edit.\n${src}`);
}
fs.writeFileSync(path.join(to, "index.ts"), FILES.map((f) => `export * from "./${f}.js";`).join("\n") + "\n");
console.log("copied shared → src/shared");
