// Writes apps/mobile/assets/content/<grade>/* and the per-grade registry.
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import type { Curriculum, Grade, Question, QuestionBundle } from "@p6/shared";
import { sanitizeId } from "./paths";

export interface FigureSource { id: string; input: string | Buffer }

export interface WriteArgs {
  grade: Grade;
  questions: Question[];
  curriculum: Omit<Curriculum, "version">;
  figures: FigureSource[];
  contentRoot: string; // .../apps/mobile/assets/content
  versionPrefix?: string;
  builtAt?: string;
}

export function sha256(s: string): string {
  return crypto.createHash("sha256").update(s).digest("hex");
}

export async function toWebp(input: string | Buffer): Promise<Buffer> {
  return sharp(input).rotate().resize({ width: 1000, withoutEnlargement: true }).webp({ quality: 75 }).toBuffer();
}

export async function writeOutputs(a: WriteArgs): Promise<{ version: string; dir: string; figureCount: number }> {
  const dir = path.join(a.contentRoot, a.grade);
  const figDir = path.join(dir, "figures");
  fs.rmSync(figDir, { recursive: true, force: true });
  fs.mkdirSync(figDir, { recursive: true });

  const sorted = [...a.questions].sort((x, y) => (x.id < y.id ? -1 : 1));
  const questions: Record<string, Question> = {};
  for (const q of sorted) questions[q.id] = q;

  // Version = sha256 of the serialized bundle (questions only, version field blank) so it is reproducible.
  const hash = sha256(JSON.stringify({ grade: a.grade, questions })).slice(0, 16);
  const version = `${a.versionPrefix ?? ""}${hash}`;
  const bundle: QuestionBundle = { grade: a.grade, version, builtAt: a.builtAt ?? new Date().toISOString(), questions };
  fs.writeFileSync(path.join(dir, "questions.json"), JSON.stringify(bundle));
  const curriculum: Curriculum = { grade: a.grade, version, topics: a.curriculum.topics };
  fs.writeFileSync(path.join(dir, "curriculum.json"), JSON.stringify(curriculum, null, 1));

  const entries: [string, string][] = [];
  for (const f of a.figures) {
    const file = `${sanitizeId(f.id)}.webp`;
    fs.writeFileSync(path.join(figDir, file), await toWebp(f.input));
    entries.push([f.id, file]);
  }
  entries.sort((x, y) => (x[0] < y[0] ? -1 : 1));
  const body = entries.map(([id, file]) => `  ${JSON.stringify(id)}: require(${JSON.stringify("./" + file)}),`).join("\n");
  fs.writeFileSync(
    path.join(figDir, "index.ts"),
    `// GENERATED by @p6/content (npm run build|mock). Do not edit.\n// Static requires: Metro needs literal paths.\n// eslint-disable-next-line @typescript-eslint/no-require-imports\nexport const figures: Record<string, number> = {\n${body}\n};\n`,
  );
  writeRegistry(a.contentRoot);
  return { version, dir, figureCount: entries.length };
}

/** Regenerates assets/content/index.ts from the grades that currently have a bundle. */
export function writeRegistry(contentRoot: string) {
  const grades = (["P4", "P5", "P6"] as Grade[]).filter((g) => fs.existsSync(path.join(contentRoot, g, "questions.json")) && fs.existsSync(path.join(contentRoot, g, "curriculum.json")));
  const lines = grades.map(
    (g) =>
      `  ${g}: {\n    bundle: require("./${g}/questions.json") as QuestionBundle,\n    curriculum: require("./${g}/curriculum.json") as Curriculum,\n    figures: require("./${g}/figures").figures as Record<string, number>,\n  },`,
  );
  const src = `// GENERATED by @p6/content (npm run build|mock). Do not edit.
// Per-grade registry: only grades that have a bundle appear here.
/* eslint-disable @typescript-eslint/no-require-imports */
import type { Curriculum, Grade, QuestionBundle } from "@p6/shared";

export interface GradeContent {
  bundle: QuestionBundle;
  curriculum: Curriculum;
  /** question id → Metro asset module id (use with <Image source={...}/>) */
  figures: Record<string, number>;
}

const registry: Partial<Record<Grade, GradeContent>> = {
${lines.join("\n")}
};

export const availableGrades = Object.keys(registry) as Grade[];

export function hasContent(grade: Grade): boolean {
  return grade in registry;
}

export function contentFor(grade: Grade): GradeContent {
  const c = registry[grade];
  if (!c) throw new Error(\`No content bundle for grade \${grade}\`);
  return c;
}
`;
  fs.mkdirSync(contentRoot, { recursive: true });
  fs.writeFileSync(path.join(contentRoot, "index.ts"), src);
}
