// GENERATED by @p6/content (npm run build|mock). Do not edit.
// Per-grade registry: only grades that have a bundle appear here.
/* eslint-disable @typescript-eslint/no-require-imports */
import type { Curriculum, Grade, QuestionBundle } from "@p6/shared";

export interface GradeContent {
  bundle: QuestionBundle;
  curriculum: Curriculum;
  /** question id → Metro asset module id (use with <Image source={...}/>) */
  figures: Record<string, number>;
}

const registry: Partial<Record<Grade, GradeContent>> = {
  P6: {
    bundle: require("./P6/questions.json") as QuestionBundle,
    curriculum: require("./P6/curriculum.json") as Curriculum,
    figures: require("./P6/figures").figures as Record<string, number>,
  },
};

export const availableGrades = Object.keys(registry) as Grade[];

export function hasContent(grade: Grade): boolean {
  return grade in registry;
}

export function contentFor(grade: Grade): GradeContent {
  const c = registry[grade];
  if (!c) throw new Error(`No content bundle for grade ${grade}`);
  return c;
}
